### PR TITLE
[docs]  clean up, get rid of not needed `eosio::` where possible

### PR DESCRIPTION
**Pull request by iamveritas**
we are making use of the `eosio` namespace so all the `eosio::` not necessary are just clobbering the code.

### CODE REVIEW

**Comment by heifner** [comment]
In my opinion this PR is a step in the wrong direction. Documentation I believe should be as descriptive as possible. I would think new users would appreciate the namespace indication to make it clear where a particular component comes from. I've always felt good example code should use explicit namespace for each type or a very close by `using` statement.

**Comment by iamveritas** [comment]
> In my opinion this PR is a step in the wrong direction. Documentation I believe should be as descriptive as possible. I would think new users would appreciate the namespace indication to make it clear where a particular component comes from. I've always felt good example code should use explicit namespace for each type or a very close by `using` statement.

**Comment by iamveritas** [comment]
> In my opinion this PR is a step in the wrong direction. Documentation I believe should be as descriptive as possible. I would think new users would appreciate the namespace indication to make it clear where a particular component comes from. I've always felt good example code should use explicit namespace for each type or a very close by `using` statement.

**Comment by tbfleming** [comment]
> another weird thing which I just notice is that I can not get rid of all the eosio::, the ones in the eosio attributes, e.g. [[eosio::contract]], can not lose it.

Correct. C++ attributes don't pay attention to scope.

**Pull request closed without merging**
