### PR TITLE
Remove db specifier from all KV APIs

### PR DESCRIPTION
**Pull request by jeffreyssmith2nd**
## Change Description

The concept of DISK mode and eosio.kvram and eosio.kvdisk are no longer valid and have been removed from the interfaces and underlying implementation.

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by jeffreyssmith2nd** [comment]
Added the do not merge label so this does not go in until the dependent PR in eos is merged

**Comment by jeffreyssmith2nd** [comment]
Note this actual depends on the entire rocksdb_nodeos_integration branch, not just the specific PR for disk removal in eos.

**Comment by nksanthosh** [comment]
Waiting for EOSIO/eos#9426 and rocksdb_nodeos_integration branch to be merged into eos/develop

**Comment by linhuang-blockone** [comment]
KV tests will fail until eosio/develop has all KV changes merged in. Bucky and Santhosh are OK with it.

**Pull request merged**
